ARG FULL_TAG=latest
FROM apluslms/grade-python:$FULL_TAG

RUN apt_install \
    bc \
    python3-matplotlib \
    python3-tk \
    python3-scipy \
    python3-numpy \
 && pip_install \
# Excel file parser is useful with pandas
    openpyxl \
    xlrd \
    xlwt \
 && :
